lang: en-US
bg_color: dark

theme_color: azure
title: Quick
description: Quick. The fastest and easiest way to make a GitHub Pages website for your project.
keywords: github pages, github readme, github pages theme, jekyll theme, landing page
gtag: G-X7HSHVZDZT

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
plugins:
  - jekyll-optional-front-matter
